# Generated by Django 5.2.4 on 2025-07-13 20:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Низкая'), ('MEDIUM', 'Средняя'), ('HIGH', 'Высокая')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='note',
            name='repeat_daily',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новое'), ('IN_PROGRESS', 'В процессе'), ('DONE', 'Выполнено')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.category'),
        ),
    ]
