# Generated by Django 5.2.4 on 2025-07-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_category_note_priority_note_repeat_daily_note_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
