# Generated by Django 5.2.4 on 2025-07-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_remove_note_date_note_end_note_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#6a11cb', max_length=7),
        ),
    ]
